# Generated by Django 5.2.13 on 2026-06-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_email_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='api_response_payload',
            field=models.JSONField(blank=True, null=True, verbose_name='JSON ответа API route'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='bitrix_contact_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Bitrix Contact ID'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='bitrix_contact_response',
            field=models.JSONField(blank=True, null=True, verbose_name='JSON ответа contact.add'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='bitrix_deal_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Bitrix Deal ID'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='bitrix_deal_response',
            field=models.JSONField(blank=True, null=True, verbose_name='JSON ответа deal.add'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='bitrix_error',
            field=models.TextField(blank=True, verbose_name='Ошибка Bitrix24'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='bitrix_status',
            field=models.CharField(choices=[('not_sent', 'Не отправлялось'), ('success', 'Успешно'), ('failed', 'Ошибка')], default='not_sent', max_length=20, verbose_name='Статус Bitrix24'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='product',
            field=models.CharField(blank=True, max_length=160, verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='request_payload',
            field=models.JSONField(blank=True, null=True, verbose_name='JSON запроса формы'),
        ),
    ]
